# Generated by Django 4.0.3 on 2022-03-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('pab_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
