# Generated by Django 4.0.3 on 2022-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0002_createpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusers',
            name='mail',
            field=models.EmailField(max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='password',
            field=models.CharField(max_length=30, unique=True, verbose_name='Пароль'),
        ),
    ]
