# Generated by Django 4.0.3 on 2022-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0003_alter_createusers_mail_alter_createusers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusers',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
