# Generated by Django 4.0.3 on 2022-04-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0004_alter_createusers_mail_alter_createusers_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='createusers',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='createpost',
            old_name='pab_date',
            new_name='pub_date',
        ),
    ]
