# Generated by Django 4.0.3 on 2022-04-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0005_alter_createpost_options_alter_createusers_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpost',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='createusers',
            old_name='uid',
            new_name='id',
        ),
    ]
