# Generated by Django 4.0.3 on 2022-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0006_rename_uid_createpost_id_rename_uid_createusers_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='createpost',
            name='imege',
            field=models.ImageField(blank=True, upload_to='post_img'),
        ),
    ]
